name: build and push container, then deploy via terraform

on:
  push:
    branches:
      - main  # or any branch you want to trigger the workflow

jobs:
  build_and_push_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: github.event_name != 'pull_request' 
        # Only login for non-PR events for security

      - name: Set up Docker Compose
        run: sudo apt-get install docker-compose
        
      - name: Build Containers with Docker Compose
        run: |
          docker-compose build
  
      - name: Push Docker images
        run: |
          docker-compose push
        if: github.event_name != 'pull_request' 
        # Only push for non-PR events for security

  terraform:
    # needs: build_and_push_docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "gcp-credentials.json"
          json: ${{ secrets.GCP_SA_CREDENTIALS }}
          dir: "."
  
      - name: Terraform Init
        run: cd terraform-GCP-deployment && terraform init
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-credentials.json
          TF_VAR_github_api_token: ${{ secrets.API_TOKEN_GITHUB }}

      # - name: Terraform Destroy
      #   run: cd terraform-GCP-deployment && terraform destroy -auto-approve
      #   env:
      #     GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-credentials.json
      #     TF_VAR_github_api_token: ${{ secrets.API_TOKEN_GITHUB }}
  
      - name: Terraform Plan
        run: cd terraform-GCP-deployment && terraform plan
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-credentials.json
          TF_VAR_github_api_token: ${{ secrets.API_TOKEN_GITHUB }}
  
      - name: Terraform Apply
        run: cd terraform-GCP-deployment && terraform apply -auto-approve
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-credentials.json
          TF_VAR_github_api_token: ${{ secrets.API_TOKEN_GITHUB }}
  
  
      # - name: Terraform Destroy
      #   run: cd terraform-GCP-deployment && terraform destroy -auto-approve
      #   env:
      #     GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-credentials.json
      #     TF_VAR_github_api_token: ${{ secrets.API_TOKEN_GITHUB }}
      #   # Here you can add any additional steps if necessary. Make sure to properly indent them as part of the 'steps' list.
  