name: build and push container, then deploy via terraform

on:
  push:
    branches:
      - main  # or any branch you want to trigger the workflow

      jobs:
        build_and_push_docker:
          runs-on: ubuntu-latest
          steps:
            - name: Checkout Code
              uses: actions/checkout@v3
      
            - name: Log in to Docker Hub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
      
            - name: Build and Push Docker Image
              uses: docker/build-push-action@v3
              with:
                context: . # Assumes Dockerfile is in the root. Adjust if it's located elsewhere.
                file: ./Dockerfile
                push: true
                tags: tty884/github-trend:latest
      
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: latest

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        TF_VAR_some_secret: ${{ secrets.SOME_SECRET }} # Example for setting up secrets

    - name: Terraform Destroy
      run: terraform destroy
    # Add any additional steps if nec