name: build and push container, then deploy via terraform

on:
  push:
    branches:
      - main  # or any branch you want to trigger the workflow

jobs:
  # build_and_push_docker:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v3

  #     - name: Log in to Docker Hub
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}

  #     - name: Build and Push Docker Image
  #       uses: docker/build-push-action@v3
  #       with:
  #         context: .
  #         file: ./Dockerfile
  #         push: true
  #         tags: tty884/github-trend:latest

  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest

      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "gcp-credentials.json"
          json: ${{ secrets.GCP_SA_CREDENTIALS }}
          dir: "."
  
      - name: Terraform Init
        run: cd terraform && terraform init
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-credentials.json

      - name: Terraform Destroy
        run: cd terraform && terraform destroy
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-credentials.json
  
      - name: Terraform Plan
        run: cd terraform && terraform plan
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-credentials.json
  
      - name: Terraform Apply
        run: cd terraform && terraform apply -auto-approve
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-credentials.json
  
  
      - name: Terraform Destroy
        run: cd terraform && terraform destroy
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-credentials.json
        # Here you can add any additional steps if necessary. Make sure to properly indent them as part of the 'steps' list.
  