name: Terraform

on:
  push:
    branches:
      - main  # or any branch you want to trigger the workflow

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.7.4 # Specify the Terraform version

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        TF_VAR_some_secret: ${{ secrets.SOME_SECRET }} # Example for setting up secrets

    - name: Terraform Destroy
      run: terraform destroy
    # Add any additional steps if nec